'use strict';

const nodemailer = require('nodemailer');

/**
 * Email notification — sends test run summary via SMTP.
 * Configure in .env:
 *   SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS,
 *   EMAIL_FROM, EMAIL_TO (comma-separated)
 */
async function sendEmailNotification(runData) {
  const host = process.env.SMTP_HOST;
  const to = process.env.EMAIL_TO;
  if (!host || !to) return null;

  const transporter = nodemailer.createTransport({
    host,
    port: parseInt(process.env.SMTP_PORT || '587', 10),
    secure: process.env.SMTP_SECURE === 'true',
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });

  const statusIcon = runData.healthScore >= 80 ? 'PASS' :
                     runData.healthScore >= 50 ? 'WARN' : 'FAIL';

  const subject = `[QA ${statusIcon}] ${runData.siteName} — ${runData.totalBugs} bugs, Health: ${runData.healthScore}%`;

  const html = `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;background:#1e1e2e;color:#e0e0e0;padding:20px;border-radius:8px;">
      <h2 style="color:#fff;border-bottom:2px solid #4f46e5;padding-bottom:10px;">QA Test Run Report</h2>
      <table style="width:100%;border-collapse:collapse;margin:15px 0;">
        <tr><td style="padding:8px;color:#a0a0a0;">Site</td><td style="padding:8px;color:#fff;font-weight:bold;">${runData.siteName}</td></tr>
        <tr><td style="padding:8px;color:#a0a0a0;">Health Score</td><td style="padding:8px;color:${runData.healthScore >= 80 ? '#22c55e' : runData.healthScore >= 50 ? '#f59e0b' : '#ef4444'};font-weight:bold;">${runData.healthScore}%</td></tr>
        <tr><td style="padding:8px;color:#a0a0a0;">Mode</td><td style="padding:8px;">${runData.mode}</td></tr>
        <tr><td style="padding:8px;color:#a0a0a0;">Duration</td><td style="padding:8px;">${runData.duration}</td></tr>
        <tr><td style="padding:8px;color:#a0a0a0;">Total Bugs</td><td style="padding:8px;font-weight:bold;">${runData.totalBugs}</td></tr>
        <tr><td style="padding:8px;color:#a0a0a0;">Critical</td><td style="padding:8px;color:#dc2626;">${runData.critical || 0}</td></tr>
        <tr><td style="padding:8px;color:#a0a0a0;">High</td><td style="padding:8px;color:#f97316;">${runData.high || 0}</td></tr>
        <tr><td style="padding:8px;color:#a0a0a0;">Medium</td><td style="padding:8px;color:#eab308;">${runData.medium || 0}</td></tr>
        <tr><td style="padding:8px;color:#a0a0a0;">Low</td><td style="padding:8px;color:#22d3ee;">${runData.low || 0}</td></tr>
        <tr><td style="padding:8px;color:#a0a0a0;">Tests</td><td style="padding:8px;">${runData.passed}/${runData.total} passed</td></tr>
        <tr><td style="padding:8px;color:#a0a0a0;">Pages</td><td style="padding:8px;">${runData.pagesLive} live / ${runData.pagesDead} dead</td></tr>
      </table>
      ${runData.reportUrl ? `<p><a href="${runData.reportUrl}" style="color:#4f46e5;text-decoration:none;font-weight:bold;">View Full Report &rarr;</a></p>` : ''}
      <p style="color:#666;font-size:12px;margin-top:20px;">Generated by Autonomous QA Agent</p>
    </div>
  `;

  try {
    await transporter.sendMail({
      from: process.env.EMAIL_FROM || process.env.SMTP_USER,
      to,
      subject,
      html,
    });
    console.log(`  [Email] Notification sent to ${to}`);
    return true;
  } catch (e) {
    console.log(`  [Email] Error: ${e.message}`);
    return false;
  }
}

module.exports = { sendEmailNotification };
